url: 'http://romaricp.github.io'
address: 'http://romaricp.github.io'

#sidebar links
email: romaric.paul@gmail.com
phone: +33 6 38 94 32 97
#website: romaricp.github.io/blog #do not add http://
linkedin: romaric-paul
github: romaricp
twitter: '@romaricp'
instagram: 'rom_a_ric'
travelgram: 'letsgetlost'
medium: '@romaricp'

# add this plugin to gems
#gems: ['jekyll-multiple-languages']

# The all languages used
#languages: ['en', 'fr']

# If not config, the first item of languages will be used as the default.
#language_default: 'en'
